services:
  - type: web
    name: phishing-api
    env: python
    buildCommand: ""
    startCommand: "gunicorn main_api:app --bind 0.0.0.0:$PORT --workers 1 --threads 4"
    plan: free
    region: oregon
